# DOCKERFILE.bin for BRANE
#   by Tim Müller and Onno Valkering
#
# Contains the Dockerfile for the various Brane instance images.
#
# This version builds the images, using precompiled binaries.
# 
# For a from-source version, see Dockerfile.rls or Dockerfile.dev.
#


##### BASE IMAGE #####
# This image defines the base image for all Brane service images.
# Note: we don't do 20.04 because the skopeo alternative link has died
# Note: we'd like to go to 22.04, but for now this is in conflict with OpenSSL
FROM ubuntu:21.10 AS brane-base
LABEL org.opencontainers.image.source https://github.com/epi-project/brane

# Install libssl (the Rust crate depends on it)
RUN apt-get update && apt-get install -y \
    libssl1.1 \
 && rm -rf /var/lib/apt/lists/*

# If ever run, run a shell
ENTRYPOINT [ "/bin/bash" ]





##### BRANE-API #####
# This image contains the Brane API service.
FROM brane-base AS brane-api

# Define the source argument
ARG SOURCE

# Install additional runtime dependencies specific for brane-api
RUN apt-get update && apt-get install -y \
    gnupg2 \
    wget \
    skopeo \
 && rm -rf /var/lib/apt/lists/*

# Copy `brane-api` from build stage
COPY $SOURCE /brane-api
RUN chmod +x /brane-api

# Run the compiled executable as base
ENTRYPOINT [ "/brane-api" ]





##### BRANE-CLB #####
# This image contains the Brane callback service.
FROM brane-base AS brane-clb

# Define the source argument
ARG SOURCE
 
# Copy `brane-clb` from build stage
COPY $SOURCE /brane-clb
RUN chmod +x /brane-clb

# Run the compiled executable as base
ENTRYPOINT [ "./brane-clb" ]





##### BRANE-DRV #####
# This image contains the Brane driver service.
FROM brane-base AS brane-drv

# Define the source argument
ARG SOURCE

# Copy `brane-drv` from build stage
COPY $SOURCE /brane-drv
RUN chmod +x /brane-drv

# Run the compiled executable as base
ENTRYPOINT [ "./brane-drv" ]





##### BRANE-JOB #####
# This image contains the Brane job service.
FROM brane-base AS brane-job

# Define the source argument
ARG SOURCE

# Copy `brane-job` from build stage
COPY $SOURCE /brane-job
RUN chmod +x /brane-job

# Run the compiled executable as base
ENTRYPOINT [ "./brane-job" ]





##### BRANE-LOG #####
# This image contains the Brane log service.
FROM brane-base AS brane-log

# Define the source argument
ARG SOURCE

# Copy `brane-log from the build stage
COPY $SOURCE /brane-log
RUN chmod +x /brane-log

# Run the compiled executable as base
ENTRYPOINT [ "./brane-log" ]





##### BRANE-PLR #####
# This image contains the Brane planner service.
FROM brane-base AS brane-plr

# Define the source argument
ARG SOURCE

# Copy `brane-plr` from build stage
COPY $SOURCE /brane-plr
RUN chmod +x /brane-plr

# Run the compiled executable as base
ENTRYPOINT [ "./brane-plr" ]
